apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploymnet
  labels:
    name: redis-app-deploymnet
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-app-pod
      app: demo-voting-app
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-app-pod
        app: demo-voting-app
    spec:
      containers:
        - name: redis-app-container
          image: redis
          resources:
            limits:
              memory: "128Mi"
              cpu: "256m"
          ports:
            - containerPort: 6379
