apiVersion: v1
kind: Service
metadata:
  name: redis # In code is hardcoded to this
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  selector:
    name: redis-app-pod
    app: demo-voting-app
  # ClusterIP, is default type
  ports:
    - port: 6379
      targetPort: 6379
