apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-pod
  labels:
    name: worker-app-deployment
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app-pod
      app: demo-voting-app
  template:
    metadata:
      name: worker-pod
      labels:
        name: worker-app-pod
        app: demo-voting-app
    spec:
      containers:
        - name: worker-container
          image: kodekloud/examplevotingapp_worker:v1
          resources:
            limits:
              memory: "512Mi"
              cpu: "1024m"
