kind: Simple
apiVersion: k3d.io/v1alpha2
name: my-simple-cluster
image: rancher/k3s:latest
servers: 1
agents: 2
ports:
- port: 80:80
  nodeFilters:
  - loadbalancer
  # options:
  #   k3s:
  #     extraServerArgs:
  #       - --no-deploy=traefik