apiVersion: v1
kind: Service
metadata:
  name: db # In code is hardcoded to this
  labels:
    name: postgres-services
    app: demo-voting-app
spec:
  selector:
    name: postgres-app-pod
    app: demo-voting-app
  # ClusterIP, is default type
  ports:
    - port: 5432
      targetPort: 5432
