apiVersion: v1
kind: Service
metadata:
  name: python-flask-sample
spec:
  selector:
    app: python-flask-sample
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  type: NodePort