apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: myredis
  name: myredis
spec:
  containers:
  - image: redis
    name: myredis
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
