apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-script-configmap
  labels:
    name: locust-script-configmap
    app: locust
data:
  locustfile.py: |
    from locust import HttpUser, between, task

    class WebSiteStressTestUsers(HttpUser):
        wait_time = between(0.7, 1.3)
        
        @task
        def stress_test_users(self):
            self.client.get("/", headers={"Host": "my.podinfo.local"})
    
