---
apiVersion: v1
kind: Service
metadata:
  name: locust-service
  labels:
    name: locust-service
    app: locust
spec:
  selector:
    name: locust-pod
    app: locust
  ports:
  - port: 8089
    targetPort: 8089
  type: LoadBalancer
