apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-sample
spec:                               # Estado que se desea
  selector:                         # Permite encontrar el pod
    matchLabels:
      app: python-flask-sample
  replicas: 3                       # Cantidad de contenedores
  template:                         # Cuando Kubernetes cree Pods (Que siga el template)
    metadata:
      labels:
        app: python-flask-sample
    spec:
      containers:
      - name: python-flask-sample
        image: ghcr.io/dieguini/python-flask-sample:main  # No usar la "latest"
        imagePullPolicy: IfNotPresent                     # Que hacer si no encuentra la imagen
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "64Mi"
            cpu: "256m"
        
