# Description: This file is for testing change commands
# check the README.md file
# Doc: README.md
# Section: Updates
apiVersion: apps/v1
kind: Deployment
metadata:
  name: update-example-deployment
  labels:
    app: update-nginx
    type: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      app: update-nginx
      type: front-end
  template:
    metadata:
      name: update-example-pod
      labels:
        app: update-nginx
        type: front-end
    spec:
      containers:
        - name: update-example-container
          image: nginx:1.7.1
